# Generated by Django 4.1.6 on 2023-04-06 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('purchase_date', models.DateTimeField(null=True)),
                ('order_status', models.CharField(choices=[('PendingAvailability', 'Pending Availability'), ('Pending', 'Pending'), ('Unshipped', 'Unshipped'), ('PartiallyShipped', 'Partially Shipped'), ('Shipped', 'Shipped'), ('InvoiceUnconfirmed', 'Invoice Unconfirmed'), ('Cancelled', 'Cancelled'), ('Unfulfillable', 'Unfulfillable')], default='Pending', max_length=19)),
                ('sales_channel', models.CharField(default='Amazon.com', max_length=19)),
                ('city', models.CharField(blank=True, default='', max_length=255)),
                ('country', models.CharField(blank=True, default='', max_length=255)),
                ('postal_code', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.CharField(blank=True, default='', max_length=255)),
                ('is_business_order', models.BooleanField(null=True)),
                ('amz_last_updated_date', models.DateTimeField(null=True)),
                ('merchant_order_id', models.CharField(blank=True, default='', max_length=255)),
                ('fufillment_channel', models.CharField(blank='', default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True, null=True)),
                ('order_item_id', models.CharField(max_length=255, unique=True)),
                ('item_status', models.CharField(choices=[('PendingAvailability', 'Pending Availability'), ('Pending', 'Pending'), ('Unshipped', 'Unshipped'), ('PartiallyShipped', 'Partially Shipped'), ('Shipped', 'Shipped'), ('InvoiceUnconfirmed', 'Invoice Unconfirmed'), ('Cancelled', 'Cancelled'), ('Unfulfillable', 'Unfulfillable')], max_length=19, null=True)),
                ('sku', models.CharField(max_length=255)),
                ('asin', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('units', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField(null=True)),
                ('reviewed', models.BooleanField(default=None, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
            ],
        ),
    ]
